services:
  vocabulary_postgres:
    container_name: vocabulary_postgresql
    image: postgres:latest
    environment:
      POSTGRES_DB: "vocabulary_db"
      POSTGRES_USER: "vocabulary_admin"
      POSTGRES_PASSWORD: "vocabularypwd"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - vocabulary_trainer

  vocabulary_trainer:
    container_name: vocabulary_trainer
    build:
      dockerfile: ./Dockerfile
    environment:
      DB_NAME: "vocabulary_db"
      DB_USER: "vocabulary_admin"
      DB_PASSWORD: "vocabularypwd"
      DB_PORT: 5432
      DB_HOST: "vocabulary_postgres"

    restart: no
    ports:
      - "8080:8080"
    networks:
      - vocabulary_trainer
networks:
  vocabulary_trainer:
    driver: bridge